name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ⏳ Install Deeps
        run: yarn install

      - name: 🔎 Verify lint
        run: yarn lint

      - name: 🩺 Unity Test
        run: yarn test

  docs:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔨 Build Docs
        run: |
          cd docs
          yarn install
          yarn build

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
